# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SLmge.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 357)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.allSerialPort = QtWidgets.QComboBox(self.centralwidget)
        self.allSerialPort.setObjectName("allSerialPort")
        self.gridLayout.addWidget(self.allSerialPort, 0, 0, 1, 1)
        self.serialPrint = QtWidgets.QTextBrowser(self.centralwidget)
        self.serialPrint.setObjectName("serialPrint")
        self.gridLayout.addWidget(self.serialPrint, 2, 0, 1, 2)
        self.openSerial = QtWidgets.QPushButton(self.centralwidget)
        self.openSerial.setObjectName("openSerial")
        self.gridLayout.addWidget(self.openSerial, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 391, 18))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.openCom = QtWidgets.QAction(MainWindow)
        self.openCom.setObjectName("openCom")
        self.viewVersion = QtWidgets.QAction(MainWindow)
        self.viewVersion.setObjectName("viewVersion")
        self.menu.addAction(self.viewVersion)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.serialPrint.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.openSerial.setText(_translate("MainWindow", "打开串口"))
        self.menu.setTitle(_translate("MainWindow", "关于"))
        self.openCom.setText(_translate("MainWindow", "打开串口"))
        self.viewVersion.setText(_translate("MainWindow", "当前版本"))
