# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SLmge.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(448, 487)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.port = QtWidgets.QComboBox(self.centralwidget)
        self.port.setEditable(False)
        self.port.setObjectName("port")
        self.gridLayout.addWidget(self.port, 1, 0, 1, 1)
        self.serialPrint = QtWidgets.QTextBrowser(self.centralwidget)
        self.serialPrint.setObjectName("serialPrint")
        self.gridLayout.addWidget(self.serialPrint, 3, 0, 1, 3)
        self.openSer = QtWidgets.QPushButton(self.centralwidget)
        self.openSer.setObjectName("openSer")
        self.gridLayout.addWidget(self.openSer, 1, 2, 1, 1)
        self.baud_label = QtWidgets.QLabel(self.centralwidget)
        self.baud_label.setObjectName("baud_label")
        self.gridLayout.addWidget(self.baud_label, 0, 1, 1, 1)
        self.baud = QtWidgets.QComboBox(self.centralwidget)
        self.baud.setObjectName("baud")
        self.gridLayout.addWidget(self.baud, 1, 1, 1, 1)
        self.port_label = QtWidgets.QLabel(self.centralwidget)
        self.port_label.setObjectName("port_label")
        self.gridLayout.addWidget(self.port_label, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 448, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpenFile = QtWidgets.QAction(MainWindow)
        self.actionOpenFile.setObjectName("actionOpenFile")
        self.menu.addAction(self.actionOpenFile)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.port, self.baud)
        MainWindow.setTabOrder(self.baud, self.openSer)
        MainWindow.setTabOrder(self.openSer, self.serialPrint)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.serialPrint.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.serialPrint.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.openSer.setText(_translate("MainWindow", "打开"))
        self.baud_label.setText(_translate("MainWindow", "波特率"))
        self.port_label.setText(_translate("MainWindow", "串口"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.actionOpenFile.setText(_translate("MainWindow", "打开文件"))
