# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addUser(object):
    def setupUi(self, addUser):
        addUser.setObjectName("addUser")
        addUser.resize(313, 244)
        self.widget = QtWidgets.QWidget(addUser)
        self.widget.setGeometry(QtCore.QRect(70, 30, 165, 172))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.userNumber = QtWidgets.QLineEdit(self.widget)
        self.userNumber.setObjectName("userNumber")
        self.gridLayout.addWidget(self.userNumber, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.major = QtWidgets.QLineEdit(self.widget)
        self.major.setObjectName("major")
        self.gridLayout.addWidget(self.major, 5, 1, 1, 1)
        self.userName = QtWidgets.QLineEdit(self.widget)
        self.userName.setObjectName("userName")
        self.gridLayout.addWidget(self.userName, 2, 1, 1, 1)
        self.sex = QtWidgets.QComboBox(self.widget)
        self.sex.setObjectName("sex")
        self.sex.addItem("")
        self.sex.addItem("")
        self.gridLayout.addWidget(self.sex, 4, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.CardID = QtWidgets.QLineEdit(self.widget)
        self.CardID.setReadOnly(True)
        self.CardID.setObjectName("CardID")
        self.gridLayout.addWidget(self.CardID, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.dialog_true = QtWidgets.QPushButton(self.widget)
        self.dialog_true.setObjectName("dialog_true")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dialog_true)
        self.dialog_false = QtWidgets.QPushButton(self.widget)
        self.dialog_false.setObjectName("dialog_false")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dialog_false)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(addUser)
        QtCore.QMetaObject.connectSlotsByName(addUser)

    def retranslateUi(self, addUser):
        _translate = QtCore.QCoreApplication.translate
        addUser.setWindowTitle(_translate("addUser", "Form"))
        self.label_4.setText(_translate("addUser", "性别"))
        self.label.setText(_translate("addUser", "姓名"))
        self.label_2.setText(_translate("addUser", "学号"))
        self.sex.setItemText(0, _translate("addUser", "男"))
        self.sex.setItemText(1, _translate("addUser", "女"))
        self.label_3.setText(_translate("addUser", "专业"))
        self.label_5.setText(_translate("addUser", "卡号"))
        self.dialog_true.setText(_translate("addUser", "确定"))
        self.dialog_false.setText(_translate("addUser", "取消"))
