# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addUser(object):
    def setupUi(self, addUser):
        addUser.setObjectName("addUser")
        addUser.resize(284, 244)
        self.gridLayout = QtWidgets.QGridLayout(addUser)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(addUser)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.CardID = QtWidgets.QLineEdit(addUser)
        self.CardID.setReadOnly(True)
        self.CardID.setObjectName("CardID")
        self.gridLayout.addWidget(self.CardID, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(addUser)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.userName = QtWidgets.QLineEdit(addUser)
        self.userName.setObjectName("userName")
        self.gridLayout.addWidget(self.userName, 1, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(addUser)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.userNumber = QtWidgets.QLineEdit(addUser)
        self.userNumber.setObjectName("userNumber")
        self.gridLayout.addWidget(self.userNumber, 2, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(addUser)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.sex = QtWidgets.QComboBox(addUser)
        self.sex.setObjectName("sex")
        self.sex.addItem("")
        self.sex.addItem("")
        self.gridLayout.addWidget(self.sex, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(addUser)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.major = QtWidgets.QLineEdit(addUser)
        self.major.setObjectName("major")
        self.gridLayout.addWidget(self.major, 4, 1, 1, 2)
        self.dialog_true = QtWidgets.QPushButton(addUser)
        self.dialog_true.setObjectName("dialog_true")
        self.gridLayout.addWidget(self.dialog_true, 5, 1, 1, 1)
        self.dialog_false = QtWidgets.QPushButton(addUser)
        self.dialog_false.setObjectName("dialog_false")
        self.gridLayout.addWidget(self.dialog_false, 5, 2, 1, 1)

        self.retranslateUi(addUser)
        QtCore.QMetaObject.connectSlotsByName(addUser)

    def retranslateUi(self, addUser):
        _translate = QtCore.QCoreApplication.translate
        addUser.setWindowTitle(_translate("addUser", "信息录入"))
        self.label_5.setText(_translate("addUser", "卡号"))
        self.label.setText(_translate("addUser", "姓名"))
        self.label_2.setText(_translate("addUser", "学号"))
        self.label_4.setText(_translate("addUser", "性别"))
        self.sex.setItemText(0, _translate("addUser", "男"))
        self.sex.setItemText(1, _translate("addUser", "女"))
        self.label_3.setText(_translate("addUser", "专业"))
        self.dialog_true.setText(_translate("addUser", "确定"))
        self.dialog_false.setText(_translate("addUser", "取消"))
